services:
  api:
    container_name: devtalles-ecommerce-api
    build:
      context: .
      dockerfile: Dockerfile
    image: devtalles-ecommerce-webapi:local
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ASPNETCORE_URLS: ${ASPNETCORE_URLS}
      ConnectionStrings__ConnectionSql: Server=${DB_HOST};Database=${DB_NAME};User ID=${DB_USER};Password=${DB_PASSWORD};TrustServerCertificate=true;MultipleActiveResultSets=true
      ApiSettings__SecretKey: ${API_SECRET_KEY}
    restart: unless-stopped
    networks:
      - miasoftnanus-network
  
networks:
  miasoftnanus-network:
    external: true
